# ci.yml
name: CI-CD
on: push
env:
  APK_NAME: LeetTutur build ${{ github.run_number }} - debug.apk
jobs:
  # CI
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.10.5
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Build the APK
        run: flutter build apk --debug
      - name: Change APK name
        run: mv "build/app/outputs/apk/release/app-release.apk" "${{ env.APK_NAME }}"
      - name: Upload apk to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: ${{ env.APK_NAME }}
          credentials: ${{ secrets.GG_SERVICE_ACCOUNT }}
          folder: 1G2HRl_f7jq_VIJy3cMrOt7DkAYjW-ilm

      - name: Print out keystore
        run: /android/gradlew signingReport
#  deploy_android:
#    runs-on: ubuntu-latest
#    needs: [ build_android ]
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Setup Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 12.x
#      - name: Decrypt Android keys
#        run: sh ./.github/scripts/decrypt_android_secrets.sh
#        env:
#          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
#      - name: Setup Flutter
#        uses: subosito/flutter-action@v1
#        with:
#          flutter-version: 2.10.4
#      - name: Install Flutter dependencies
#        run: flutter pub get
#      - name: Build the apk
#        run: flutter build apk --release
#      - name: Run Fastlane
#        uses: maierj/fastlane-action@v1.4.0
#        with:
#          lane: closed_beta
#          subdirectory: android
#
